name: Convert Issues to CSV

on:
  issues:
    types: [opened, edited, reopened]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Create drink_log.csv
        run: |
          echo "日付,プッシュ数,リットル数,メモ" > data/drink_log.csv
          gh issue list --label drink --state all --limit 1000 --json title,body | jq -r '
            if type == "array" then
              .[]
              | [
                  (.title | try capture("(?<date>\\d{4}-\\d{2}-\\d{2})").date catch ""),
                  (.body | try capture("プッシュ数: (?<push>\\d+)").push catch ""),
                  (.body | try capture("リットル: (?<liters>[\\d\\.]+)").liters catch ""),
                  (.body | try capture("メモ: (?<memo>.*)").memo catch "")
                ] | @csv
            else
              empty
            end
          ' >> data/drink_log.csv
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}          

      - name: Create gas_log.csv
        run: |
          echo "日付,メモ" > data/gas_log.csv
          gh issue list --label gas_change --state all --limit 1000 --json title,body | jq -r '
            .[] |
            [.title | capture("(?<date>\\d{4}-\\d{2}-\\d{2})").date,
             (.body | capture("メモ: (?<memo>.*)").memo)] |
            @csv
          ' >> data/gas_log.csv
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}          


      - name: Commit and push CSV files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          git commit -m "Update CSV logs from issues" || echo "No changes to commit"
          git push origin HEAD
